#include "word_game.h"
/* Original practice list; not an official IELTS vocabulary list. */
const WgWord wg_words[] = {
    {"sustainable", "可持续的", "Environment", "able to continue without using up resources"},
    {"biodiversity", "生物多样性", "Environment", "the variety of living species in an area"},
    {"conservation", "保护；保育", "Environment", "protection of nature and natural resources"},
    {"emission", "排放", "Environment", "a substance released into the air"},
    {"renewable", "可再生的", "Environment", "able to be naturally replaced"},
    {"habitat", "栖息地", "Environment", "the natural home of an animal or plant"},
    {"curriculum", "课程体系", "Education", "all the subjects taught in a course"},
    {"literacy", "读写能力", "Education", "ability to read and write"},
    {"assessment", "评估", "Education", "the process of judging quality or ability"},
    {"qualification", "资格；资历", "Education", "an official record of skills or education"},
    {"tuition", "学费；教学", "Education", "money paid for teaching or instruction"},
    {"scholarship", "奖学金", "Education", "money awarded to support a student"},
    {"innovation", "创新", "Technology", "a new idea, method or invention"},
    {"automation", "自动化", "Technology", "use of machines to perform tasks"},
    {"infrastructure", "基础设施", "Technology", "basic systems such as roads and power"},
    {"privacy", "隐私", "Technology", "freedom from unwanted public attention"},
    {"accessible", "可使用的；易接近的", "Technology", "easy for people to reach or use"},
    {"obsolete", "过时的", "Technology", "no longer used because something is newer"},
    {"inequality", "不平等", "Society", "an unfair difference between groups"},
    {"migration", "迁移；移民", "Society", "movement of people to another place"},
    {"urbanization", "城市化", "Society", "growth of towns and cities"},
    {"demographic", "人口统计的", "Society", "relating to the structure of a population"},
    {"employment", "就业", "Society", "the state of having paid work"},
    {"legislation", "立法；法规", "Society", "laws made by a government"},
    {"evidence", "证据", "Academic", "facts that support or disprove a claim"},
    {"hypothesis", "假设", "Academic", "an idea proposed for testing"},
    {"significant", "显著的；重要的", "Academic", "important or large enough to matter"},
    {"evaluate", "评价；评估", "Academic", "to judge the value or quality of something"},
    {"consequence", "后果", "Academic", "a result of an action or situation"},
    {"perspective", "观点；视角", "Academic", "a particular way of viewing a situation"},
    {"nutrition", "营养", "Health", "food and nutrients needed for health"},
    {"sedentary", "久坐的", "Health", "involving much sitting and little exercise"},
    {"prevention", "预防", "Health", "action taken to stop something happening"},
    {"wellbeing", "身心健康", "Health", "a state of being healthy and content"},
    {"diagnosis", "诊断", "Health", "identification of an illness or problem"},
    {"recovery", "康复；恢复", "Health", "a return to health or a normal condition"},
};
const size_t wg_word_count = sizeof(wg_words) / sizeof(wg_words[0]);
